#+hugo_base_dir: ../

#+TITLE: Building an Emacs Like Text Editor in C
#+DATE: 2022-08-30
#+AUTHOR: "Abhinav Chavali"

#+HUGO_DRAFT: true
#+HUGO_TAGS: Emacs Unix C
#+HUGO_CATEGORIES: Programming

* Building an Emacs Like Text Editor in C

[[https://git.dumrich.com/chabi/cemacs][Repo Link]]

Over the past couple months, I've been working on a text editor that aims to fix many of the hardships that I've faced as a GNU/Emacs user over the past few months. Specifically, I wanted to keep the core ideas of Emacs, but make some improvements, especially:
- Using a custom compiled Scheme over Emacs Lisp, with a simple API
- Few dependencies
- Fast, multithreaded design
- Better UI
- Minibuffer is a popup
- Should be very simple (a basic programmer should be able to master all of it in a day), and also powerful
- Intuitive  keybindings

It currently depends only on ncurses, with a GTK backend in the works. Clone, and run ~make~, followed by ~make install~.

** Features
The editor takes inspiration from many different editors, especially GNU/Emacs and Neovim. As such, I've included some convencience features from these softwares:
- UTF-8 Text Editing
- Integrated Terminal Emulator
- Custom git wrapper based on ~libgit2~
- OOTB SSH Editing
- Compiled Scheme configuration language with 100+ functions integrating with the editor
- Multi-tabbed Popup window
- Dired
- Statusbar
- Dashboard


The *book*, located at ./book/, gives a complete look at the software from a user's perspective.

** Architecture
Code blocks

#+begin_src C
  #include <stdio.h>

  int main(int argc, char** argv);
#+end_src
