#+hugo_base_dir: ../

#+TITLE: Rocky III (1982) Movie Review
#+DATE: 2022-10-17
#+AUTHOR: "Abhinav Chavali"

#+HUGO_DRAFT: false
#+HUGO_TAGS: Action 80s
#+HUGO_CATEGORIES: Movies

* Rocky III (1982)
Rocky Balboa (Sylvester Stallone) takes on Clubber Lang (Mr. T) in the third installment of the Rocky series.

Rating: *4/5*

** Synopsis
Rocky Balboa is now a boxing legend, defending his title (gained in his last bout with Apollo Creed) many times over against cherry picked opponents. He is famous and wealthy as a boxer, frequently filming commericials and appearing in billboards. When Balboa announces his retirement, one Clubber Lang calls him out for the last match of his career.

Rocky trains for the match, though not with the same passion as before. Thus, when their first fight comes, Clubber pummels Rocky, and kills his trainer Mick.

Bored with retirement, Apollo Creed decides to train Rocky at his old gym in Los Angeles. At first, Rocky is docile, clearly missing his old hunger. After speeches from Adrianne (Talia Shire) and Apollo, he whips into the best shape of his career, finally defeating Lang.
** Review
This was a very solid addition to my favorite movie franchise ever. We see rivals become friends to overcome the new villain. This calls for some great lines, including my favorite in the movie:

#+ATTR_TEXINFO: :author Apollo Creed
#+begin_quote
 "There is no tomorrow! There is no tomorrow!"
#+end_quote

During each of these films, I'd always wondered why Rocky tolerated Paulie (Burt Young). Paulie was a loser who expected everything to be handed to him.

I also wondered how Apollo Creed would fare against Clubber Lang. I feel like Rocky was essentially Apollo after being trained by him, so prime Apollo could likely take Clubber.

I felt that the movie could have been paced a little bit better. The first half was very slow, but the second half was really great. As many have pointed out, the whole Thunderlips scene added nothing to the movie, but I liked it nonetheless.

Notable lines:
#+ATTR_TEXINFO: :author Clubber Lang
#+begin_quote
"No, I don't hate Balboa. I pity the fool, and I will destroy any man who tries to take what I got!"
#+end_quote

#+ATTR_TEXINFO: :author Mickey Goldmill
#+begin_quote
"The worst thing that happened to you, that can happen to any fighter: you got civilized."
#+end_quote
